// Code generated by cmd/reset. DO NOT EDIT.

package models

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if r.child != nil {
		if resetter, ok := interface{}(r.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}

func (r *ComplexStruct) Reset() {
	if r == nil {
		return
	}

	r.intVal = 0
	r.int64Val = 0
	r.uintVal = 0
	r.floatVal = 0
	r.boolVal = false
	r.stringVal = ""
	if r.intPtr != nil {
		*r.intPtr = 0
	}
	if r.stringPtr != nil {
		*r.stringPtr = ""
	}
	if r.boolPtr != nil {
		*r.boolPtr = false
	}
	r.slice = r.slice[:0]
	r.intSlice = r.intSlice[:0]
	clear(r.mapData)
	clear(r.mapString)
	if resetter, ok := interface{}(&r.nested).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if r.nestedP != nil {
		if resetter, ok := interface{}(r.nestedP).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
